feat: :construction: start of work on creating sidecar mode

diff --git a/connector-restart b/connector-restart
--- a/connector-restart
+++ b/connector-restart
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-set -e
+#set -e
 
 # Messages
 log () {
@@ -22,33 +22,52 @@ warn () {
   else log WARNING "$*"; fi
 }
 
+KAFKA_CONNECT_HOST=localhost
+KAFKA_CONNECT_PORT=8083
 
 #Set vars
+launch_mode="${launch_mode:-$LAUNCH_MODE}"
 kafka_connect_host="${kafka_connect_host:-$KAFKA_CONNECT_HOST}"
 kafka_connect_port="${kafka_connect_port:-$KAFKA_CONNECT_PORT}"
-
+request_delay="${request_delay:-$REQUEST_DELAY}"
+request_timeout="${request_timeout:-$REQUEST_TIMEOUT}"
 
 #Print vars
+info LAUNCH_MODE="$launch_mode"
 info KAFKA_CONNECT_HOST="$kafka_connect_host"
 info KAFKA_CONNECT_PORT="$kafka_connect_port"
+info REQUEST_DELAY="$request_delay"
+info REQUEST_TIMEOUT="$request_timeout"
 
-
-
-connectorsjson=$(
-  curl -s "http://$kafka_connect_host:$kafka_connect_port/connectors?expand=status"
-) 
-
-status=$?
-if [ $status -eq 0 ]
+if $launch_mode == SIDECAR
 then
 
-  # List current connectors and status
-  echo connectorsjson | \ 
-    jq -c -M 'map({name: .status.name } +  {tasks: .status.tasks}) | .[] | {task: ((.tasks[]) + {name: .name})} | select(.task.state=="FAILED") | {name: .task.name, task_id: .task.id|tostring} | ("/connectors/"+ .name + "/tasks/" + .task_id + "/restart")' | \
-    xargs -I{connector_and_task} curl -v -X POST "http://$kafka_connect_host:$kafka_connect_port"\{connector_and_task\}
+  connectorsjson=$(
+    curl -Lff "http://$kafka_connect_host:$kafka_connect_port/connectors?expand=status"
+  ) 
+
+  status=$?
+  if [ $status -eq 0 ]
+  then
+
+    # List current connectors and status
+    echo connectorsjson | \ 
+      jq '. | to_entries[] | [ .value.info.type, .key, .value.status.connector.state,.value.status.tasks[].state,.value.info.config."connector.class"]|join(":|:")' | \
+      column -s : -t| sed 's/\"//g'| sort
+
+    # # Restart any connector tasks that are FAILED
+    # curl -s "http://$kafka_connect_host:$kafka_connect_port/connectors?expand=status" | \
+    #   jq -c -M 'map({name: .status.name } +  {tasks: .status.tasks}) | .[] | {task: ((.tasks[]) + {name: .name})} | select(.task.state=="FAILED") | {name: .task.name, task_id: .task.id|tostring} | ("/connectors/"+ .name + "/tasks/" + .task_id + "/restart")' | \
+    #   xargs -I{connector_and_task} curl -v -X POST "http://$kafka_connect_host:$kafka_connect_port"\{connector_and_task\}
+
+  else
+    fail 'Connect to API Kafka Connect' \
+    http://$kafka_connect_host:$kafka_connect_port \
+    'failed with status code' $status 'and message' $connectorsjson
+  fi
 
 else
-  fail 'Connect to API Kafka Connect' \
-   http://$kafka_connect_host:$kafka_connect_port \
-   'failed with status code' $status
+    echo connectorsjson | \ 
+    jq -c -M 'map({name: .status.name } +  {tasks: .status.tasks}) | .[] | {task: ((.tasks[]) + {name: .name})} | select(.task.state=="FAILED") | {name: .task.name, task_id: .task.id|tostring} | ("/connectors/"+ .name + "/tasks/" + .task_id + "/restart")' | \
+    xargs -I{connector_and_task} curl -v -X POST "http://$kafka_connect_host:$kafka_connect_port"\{connector_and_task\}
 fi
