fix env, fix sidecar mode,

diff --git a/connector-restart b/connector-restart
--- a/connector-restart
+++ b/connector-restart
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#set -e
+set -e
 
 # Messages
 log () {
@@ -22,52 +22,53 @@ warn () {
   else log WARNING "$*"; fi
 }
 
-KAFKA_CONNECT_HOST=localhost
-KAFKA_CONNECT_PORT=8083
-
 #Set vars
-launch_mode="${launch_mode:-$LAUNCH_MODE}"
-kafka_connect_host="${kafka_connect_host:-$KAFKA_CONNECT_HOST}"
-kafka_connect_port="${kafka_connect_port:-$KAFKA_CONNECT_PORT}"
-request_delay="${request_delay:-$REQUEST_DELAY}"
-request_timeout="${request_timeout:-$REQUEST_TIMEOUT}"
+: "${SIDECAR_MODE:=false}"
+: "${KAFKA_CONNECT_HOST:=localhost}"
+: "${KAFKA_CONNECT_PORT:=8083}"
+: "${REQUEST_DELAY:=30}"
 
 #Print vars
-info LAUNCH_MODE="$launch_mode"
-info KAFKA_CONNECT_HOST="$kafka_connect_host"
-info KAFKA_CONNECT_PORT="$kafka_connect_port"
-info REQUEST_DELAY="$request_delay"
-info REQUEST_TIMEOUT="$request_timeout"
+info SIDECAR_MODE="$SIDECAR_MODE"
+info KAFKA_CONNECT_HOST="$KAFKA_CONNECT_HOST"
+info KAFKA_CONNECT_PORT="$KAFKA_CONNECT_PORT"
+info REQUEST_DELAY="$REQUEST_DELAY"
 
-if $launch_mode == SIDECAR
+if [ "$SIDECAR_MODE" = true ]
 then
-
-  connectorsjson=$(
-    curl -Lff "http://$kafka_connect_host:$kafka_connect_port/connectors?expand=status"
-  ) 
-
-  status=$?
-  if [ $status -eq 0 ]
+  while true 
+    do 
+      if connectorsjson=$(
+        curl -Lff "http://$KAFKA_CONNECT_HOST:$KAFKA_CONNECT_PORT/connectors?expand=status"
+        )
+      then
+        # List current connectors and status
+        echo connectorsjson | \
+          jq '. | to_entries[] | [ .value.info.type, .key, .value.status.connector.state,.value.status.tasks[].state,.value.info.config."connector.class"]|join(":|:")' | \
+          column -s : -t| sed 's/\"//g'| sort
+        # Restart any connector tasks that are FAILED
+        echo connectorsjson | \
+          jq -c -M 'map({name: .status.name } +  {tasks: .status.tasks}) | .[] | {task: ((.tasks[]) + {name: .name})} | select(.task.state=="FAILED") | {name: .task.name, task_id: .task.id|tostring} | ("/connectors/"+ .name + "/tasks/" + .task_id + "/restart")' | \
+          xargs -I{connector_and_task} curl -v -X POST "http://$KAFKA_CONNECT_HOST:$KAFKA_CONNECT_PORT"\{connector_and_task\}
+      else
+        fail 'Connect to API Kafka Connect' \
+        http://$KAFKA_CONNECT_HOST:$KAFKA_CONNECT_PORT \
+        'failed with status code' $? 'and message' $connectorsjson
+      fi
+      sleep "$REQUEST_DELAY"m
+    done
+else
+  if connectorsjson=$(
+    curl -Lff "http://$KAFKA_CONNECT_HOST:$KAFKA_CONNECT_PORT/connectors?expand=status"
+    )
   then
-
-    # List current connectors and status
-    echo connectorsjson | \ 
-      jq '. | to_entries[] | [ .value.info.type, .key, .value.status.connector.state,.value.status.tasks[].state,.value.info.config."connector.class"]|join(":|:")' | \
-      column -s : -t| sed 's/\"//g'| sort
-
-    # # Restart any connector tasks that are FAILED
-    # curl -s "http://$kafka_connect_host:$kafka_connect_port/connectors?expand=status" | \
-    #   jq -c -M 'map({name: .status.name } +  {tasks: .status.tasks}) | .[] | {task: ((.tasks[]) + {name: .name})} | select(.task.state=="FAILED") | {name: .task.name, task_id: .task.id|tostring} | ("/connectors/"+ .name + "/tasks/" + .task_id + "/restart")' | \
-    #   xargs -I{connector_and_task} curl -v -X POST "http://$kafka_connect_host:$kafka_connect_port"\{connector_and_task\}
-
+    # Restart any connector tasks that are FAILED
+    echo connectorsjson | \
+    jq -c -M 'map({name: .status.name } +  {tasks: .status.tasks}) | .[] | {task: ((.tasks[]) + {name: .name})} | select(.task.state=="FAILED") | {name: .task.name, task_id: .task.id|tostring} | ("/connectors/"+ .name + "/tasks/" + .task_id + "/restart")' | \
+    xargs -I{connector_and_task} curl -v -X POST "http://$KAFKA_CONNECT_HOST:$KAFKA_CONNECT_PORT"\{connector_and_task\}
   else
     fail 'Connect to API Kafka Connect' \
-    http://$kafka_connect_host:$kafka_connect_port \
-    'failed with status code' $status 'and message' $connectorsjson
+    http://$KAFKA_CONNECT_HOST:$KAFKA_CONNECT_PORT \
+    'failed with status code' $? 'and message' $connectorsjson
   fi
-
-else
-    echo connectorsjson | \ 
-    jq -c -M 'map({name: .status.name } +  {tasks: .status.tasks}) | .[] | {task: ((.tasks[]) + {name: .name})} | select(.task.state=="FAILED") | {name: .task.name, task_id: .task.id|tostring} | ("/connectors/"+ .name + "/tasks/" + .task_id + "/restart")' | \
-    xargs -I{connector_and_task} curl -v -X POST "http://$kafka_connect_host:$kafka_connect_port"\{connector_and_task\}
 fi
